// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	film "github.com/migalpha/kentech-films"
	mock "github.com/stretchr/testify/mock"
)

// FavouriteSaver is an autogenerated mock type for the FavouriteSaver type
type FavouriteSaver struct {
	mock.Mock
}

// Save provides a mock function with given fields: _a0
func (_m *FavouriteSaver) Save(_a0 film.Favourite) (film.FavouriteID, error) {
	ret := _m.Called(_a0)

	var r0 film.FavouriteID
	if rf, ok := ret.Get(0).(func(film.Favourite) film.FavouriteID); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(film.FavouriteID)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(film.Favourite) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
