// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	context "context"

	film "github.com/migalpha/kentech-films"
	mock "github.com/stretchr/testify/mock"
)

// FavouriteDestroyer is an autogenerated mock type for the FavouriteDestroyer type
type FavouriteDestroyer struct {
	mock.Mock
}

// Destroy provides a mock function with given fields: _a0, _a1, _a2
func (_m *FavouriteDestroyer) Destroy(_a0 context.Context, _a1 film.FilmID, _a2 film.UserID) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, film.FilmID, film.UserID) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
