// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	film "github.com/migalpha/kentech-films"
	mock "github.com/stretchr/testify/mock"
)

// FilmSaver is an autogenerated mock type for the FilmSaver type
type FilmSaver struct {
	mock.Mock
}

// Save provides a mock function with given fields: _a0
func (_m *FilmSaver) Save(_a0 film.Film) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(film.Film) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
