// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	film "github.com/migalpha/kentech-films"
	mock "github.com/stretchr/testify/mock"
)

// FilmDestroyer is an autogenerated mock type for the FilmDestroyer type
type FilmDestroyer struct {
	mock.Mock
}

// Destroy provides a mock function with given fields: _a0
func (_m *FilmDestroyer) Destroy(_a0 film.FilmID) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(film.FilmID) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
